// 内置模型表数据 —— 由官方 ListModels API 一次性拉取后生成
// 生成工具：scripts/gen-models.mjs（仓库内，可在面板外手动重生成）
// 数据来源：GET {gemini_base}/v1beta/models?pageSize=1000（x-goog-api-key 鉴权）
// 拉取时间：2026-09-05，共 54 个模型
//
// 分类规则（运行时由 src/modellist.ts 的 classifyModels 执行）：
//   chat        —— supportedGenerationMethods 含 generateContent（OpenAI/Anthropic/Gemini 三入口可用）
//   native_only —— 仅 predict / predictLongRunning（Gemini 原生透传 :predict / :predictLongRunning）
//   excluded    —— 仅 embedContent / generateAnswer / bidiGenerateContent（本代理不透传，自动排除）

export const BUILTIN_FETCHED_AT = "2026-09-05";

export interface BuiltinModelMeta {
  name: string;
  display_name?: string;
  description?: string;
  version?: string;
  input_token_limit?: number;
  output_token_limit?: number;
  methods: string[];
  thinking?: boolean;
  temperature?: number;
  top_p?: number;
  top_k?: number;
}

export const BUILTIN_MODEL_META: BuiltinModelMeta[] = [
  {"name": "gemini-2.5-flash", "display_name": "Gemini 2.5 Flash", "description": "Stable version of Gemini 2.5 Flash, our mid-size multimodal model that supports up to 1 million tokens, released in June of 2025.", "version": "001", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-2.5-pro", "display_name": "Gemini 2.5 Pro", "description": "Stable release (June 17th, 2025) of Gemini 2.5 Pro", "version": "2.5", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-2.5-flash-preview-tts", "display_name": "Gemini 2.5 Flash Preview TTS", "description": "Gemini 2.5 Flash Preview TTS", "version": "gemini-2.5-flash-exp-tts-2025-05-19", "input_token_limit": 8192, "output_token_limit": 16384, "methods": ["countTokens", "generateContent"], "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-2.5-pro-preview-tts", "display_name": "Gemini 2.5 Pro Preview TTS", "description": "Gemini 2.5 Pro Preview TTS", "version": "gemini-2.5-pro-preview-tts-2025-05-19", "input_token_limit": 8192, "output_token_limit": 16384, "methods": ["countTokens", "generateContent", "batchGenerateContent"], "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemma-4-26b-a4b-it", "display_name": "Gemma 4 26B A4B IT", "description": "Gemma 4 26B A4B IT", "version": "001", "input_token_limit": 262144, "output_token_limit": 32768, "methods": ["generateContent", "countTokens"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemma-4-31b-it", "display_name": "Gemma 4 31B IT", "description": "Gemma 4 31B IT", "version": "001", "input_token_limit": 262144, "output_token_limit": 32768, "methods": ["generateContent", "countTokens"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-flash-latest", "display_name": "Gemini Flash Latest", "description": "Latest release of Gemini Flash", "version": "Gemini Flash Latest", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-flash-lite-latest", "display_name": "Gemini Flash-Lite Latest", "description": "Latest release of Gemini Flash-Lite", "version": "Gemini Flash-Lite Latest", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-pro-latest", "display_name": "Gemini Pro Latest", "description": "Latest release of Gemini Pro", "version": "Gemini Pro Latest", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-2.5-flash-lite", "display_name": "Gemini 2.5 Flash-Lite", "description": "Stable version of Gemini 2.5 Flash-Lite, released in July of 2025", "version": "001", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-2.5-flash-image", "display_name": "Nano Banana", "description": "Gemini 2.5 Flash Preview Image", "version": "2.0", "input_token_limit": 32768, "output_token_limit": 32768, "methods": ["generateContent", "countTokens", "batchGenerateContent"], "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3-flash-preview", "display_name": "Gemini 3 Flash Preview", "description": "Gemini 3 Flash Preview", "version": "3-flash-preview-12-2025", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3.1-pro-preview", "display_name": "Gemini 3.1 Pro Preview", "description": "Gemini 3.1 Pro Preview", "version": "3.1-pro-preview-01-2026", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3.1-pro-preview-customtools", "display_name": "Gemini 3.1 Pro Preview Custom Tools", "description": "Gemini 3.1 Pro Preview optimized for custom tool usage", "version": "3.1-pro-preview-01-2026", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3.1-flash-lite-preview", "display_name": "Gemini 3.1 Flash Lite Preview", "description": "Gemini 3.1 Flash Lite Preview", "version": "3.1-flash-lite-preview-03-2026", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3.1-flash-lite", "display_name": "Gemini 3.1 Flash Lite", "description": "Gemini 3.1 Flash Lite", "version": "3.1-flash-lite-05-2026", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3-pro-image-preview", "display_name": "Nano Banana Pro", "description": "Gemini 3 Pro Image Preview", "version": "3.0", "input_token_limit": 131072, "output_token_limit": 32768, "methods": ["generateContent", "countTokens", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3-pro-image", "display_name": "Nano Banana Pro", "description": "Gemini 3 Pro Image", "version": "3.0", "input_token_limit": 131072, "output_token_limit": 32768, "methods": ["generateContent", "countTokens", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "nano-banana-pro-preview", "display_name": "Nano Banana Pro", "description": "Gemini 3 Pro Image Preview", "version": "3.0", "input_token_limit": 131072, "output_token_limit": 32768, "methods": ["generateContent", "countTokens", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3.1-flash-image-preview", "display_name": "Nano Banana 2", "description": "Gemini 3.1 Flash Image Preview.", "version": "3.0", "input_token_limit": 65536, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3.1-flash-image", "display_name": "Nano Banana 2", "description": "Gemini 3.1 Flash Image.", "version": "3.0", "input_token_limit": 65536, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3.1-flash-lite-image", "display_name": "Nano Banana 2 Lite", "description": "Gemini 3.1 Flash Lite Image.", "version": "3.0", "input_token_limit": 65536, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3.5-flash", "display_name": "Gemini 3.5 Flash", "description": "Gemini 3.5 Flash", "version": "3.5-flash-05-2026", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3.5-flash-lite", "display_name": "Gemini 3.5 Flash Lite", "description": "Gemini 3.5 Flash Lite", "version": "3.5-flash-lite-07-2026", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-omni-flash-preview", "display_name": "Gemini Omni Flash Preview", "description": "Gemini Omni Flash Preview", "version": "001", "input_token_limit": 131072, "output_token_limit": 65536, "methods": ["generateContent", "countTokens"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-omni-1.1-flash", "display_name": "Gemini Omni 1.1 Flash", "description": "Gemini Omni 1.1 Flash ", "version": "001", "input_token_limit": 131072, "output_token_limit": 65536, "methods": ["generateContent", "countTokens"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3.5-transcribe", "display_name": "Gemini 3.5 Transcribe", "description": "Gemini 3.5 Transcribe", "version": "3.5-transcribe-08-2026", "input_token_limit": 98304, "output_token_limit": 32768, "methods": ["generateContent", "countTokens"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3.6-flash", "display_name": "Gemini 3.6 Flash", "description": "Gemini 3.6 Flash", "version": "3.6-flash-07-2026", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3.7-flash", "display_name": "Gemini 3.7 Flash", "description": "Gemini 3.7 Flash", "version": "3.7-flash-08-2026", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3.8-flash", "display_name": "Gemini 3.8 Flash", "description": "Gemini 3.8 Flash", "version": "3.0", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "lyria-3-clip-preview", "display_name": "Lyria 3 Clip Preview", "description": "Lyria 3 30s model Preview", "version": "lyria-3-clip-preview", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens"], "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "lyria-3-pro-preview", "display_name": "Lyria 3 Pro Preview", "description": "Lyria 3 Pro Preview", "version": "lyria-3-pro-preview", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens"], "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "lyria-3.5", "display_name": "Lyria 3.5", "description": "Music Generation model", "version": "3.5", "input_token_limit": 1048576, "output_token_limit": 65536, "methods": ["generateContent", "countTokens"], "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3.1-flash-tts-preview", "display_name": "Gemini 3.1 Flash TTS Preview", "description": "Gemini 3.1 Flash TTS Preview", "version": "3.1-flash-tts-preview", "input_token_limit": 8192, "output_token_limit": 16384, "methods": ["generateContent", "countTokens", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-robotics-er-2-preview", "display_name": "Gemini Robotics-ER 2 Preview", "description": "Gemini Robotics-ER 2 Preview", "version": "2-preview", "input_token_limit": 131072, "output_token_limit": 65536, "methods": ["generateContent", "countTokens", "createCachedContent", "batchGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-2.5-computer-use-preview-10-2025", "display_name": "Gemini 2.5 Computer Use Preview 10-2025", "description": "Gemini 2.5 Computer Use Preview 10-2025", "version": "Gemini 2.5 Computer Use Preview 10-2025", "input_token_limit": 131072, "output_token_limit": 65536, "methods": ["generateContent", "countTokens"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "antigravity-preview-05-2026", "display_name": "Antigravity Agent Preview", "description": "Preview release of Antigravity Agent (05-2026)", "version": "0.1", "input_token_limit": 131072, "output_token_limit": 65536, "methods": ["generateContent", "countTokens"]},
  {"name": "deep-research-max-preview-04-2026", "display_name": "Deep Research Max Preview (Apr-21-2026)", "description": "Preview release (April 21st, 2026) of Deep Research Max", "version": "deepthink-exp-05-20", "input_token_limit": 131072, "output_token_limit": 65536, "methods": ["generateContent", "countTokens"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "deep-research-preview-04-2026", "display_name": "Deep Research Preview (Apr-21-2026)", "description": "Preview release (April 21th, 2026) of Deep Research", "version": "deepthink-exp-05-20", "input_token_limit": 131072, "output_token_limit": 65536, "methods": ["generateContent", "countTokens"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "deep-research-pro-preview-12-2025", "display_name": "Deep Research Pro Preview (Dec-12-2025)", "description": "Preview release (December 12th, 2025) of Deep Research Pro", "version": "deepthink-exp-05-20", "input_token_limit": 131072, "output_token_limit": 65536, "methods": ["generateContent", "countTokens"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-embedding-001", "display_name": "Gemini Embedding 001", "description": "Obtain a distributed representation of a text.", "version": "001", "input_token_limit": 2048, "output_token_limit": 1, "methods": ["embedContent", "countTextTokens", "countTokens", "asyncBatchEmbedContent"]},
  {"name": "gemini-embedding-2-preview", "display_name": "Gemini Embedding 2 Preview", "description": "Obtain a distributed representation of multimodal content.", "version": "2", "input_token_limit": 8192, "output_token_limit": 1, "methods": ["embedContent", "countTextTokens", "countTokens", "asyncBatchEmbedContent"]},
  {"name": "gemini-embedding-2", "display_name": "Gemini Embedding 2", "description": "Obtain a distributed representation of multimodal content.", "version": "2", "input_token_limit": 8192, "output_token_limit": 1, "methods": ["embedContent", "countTextTokens", "countTokens", "asyncBatchEmbedContent"]},
  {"name": "aqa", "display_name": "Model that performs Attributed Question Answering.", "description": "Model trained to return answers to questions that are grounded in provided sources, along with estimating answerable probability.", "version": "001", "input_token_limit": 7168, "output_token_limit": 1024, "methods": ["generateAnswer"], "temperature": 0.2, "top_p": 1, "top_k": 40},
  {"name": "veo-3.1-generate-preview", "display_name": "Veo 3.1", "description": "Veo 3.1", "version": "3.1", "input_token_limit": 480, "output_token_limit": 8192, "methods": ["predictLongRunning"]},
  {"name": "veo-3.1-fast-generate-preview", "display_name": "Veo 3.1 fast", "description": "Veo 3.1 fast", "version": "3.1", "input_token_limit": 480, "output_token_limit": 8192, "methods": ["predictLongRunning"]},
  {"name": "veo-3.1-lite-generate-preview", "display_name": "Veo 3.1 lite", "description": "Veo 3.1 lite", "version": "3.1", "input_token_limit": 480, "output_token_limit": 8192, "methods": ["predictLongRunning"]},
  {"name": "gemini-3.5-transcribe-live", "display_name": "Gemini 3.5 Transcribe Live", "description": "Gemini 3.5 Transcribe Live", "version": "3.5-transcribe-live-08-2026", "input_token_limit": 131072, "output_token_limit": 65536, "methods": ["bidiGenerateContent"], "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-2.5-flash-native-audio-latest", "display_name": "Gemini 2.5 Flash Native Audio Latest", "description": "Latest release of Gemini 2.5 Flash Native Audio", "version": "Gemini 2.5 Flash Native Audio Latest", "input_token_limit": 131072, "output_token_limit": 8192, "methods": ["countTokens", "bidiGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-2.5-flash-native-audio-preview-09-2025", "display_name": "Gemini 2.5 Flash Native Audio Preview 09-2025", "description": "Gemini 2.5 Flash Native Audio Preview 09-2025", "version": "gemini-2.5-flash-preview-native-audio-dialog-2025-05-19", "input_token_limit": 131072, "output_token_limit": 8192, "methods": ["countTokens", "bidiGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-2.5-flash-native-audio-preview-12-2025", "display_name": "Gemini 2.5 Flash Native Audio Preview 12-2025", "description": "Gemini 2.5 Flash Native Audio Preview 12-2025", "version": "12-2025", "input_token_limit": 131072, "output_token_limit": 8192, "methods": ["countTokens", "bidiGenerateContent"], "thinking": true, "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3.1-flash-live-preview", "display_name": "Gemini 3.1 Flash Live Preview", "description": "Gemini 3.1 Flash Live Preview", "version": "3.1-flash-live-03-2026", "input_token_limit": 131072, "output_token_limit": 65536, "methods": ["bidiGenerateContent"], "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-robotics-er-2-streaming-preview", "display_name": "Gemini Robotics-ER 2 Streaming Preview", "description": "Gemini Robotics-ER 2 Streaming Preview", "version": "2-streaming-preview", "input_token_limit": 131072, "output_token_limit": 65536, "methods": ["bidiGenerateContent"], "temperature": 1, "top_p": 0.95, "top_k": 64},
  {"name": "gemini-3.5-live-translate-preview", "display_name": "Gemini 3.5 Live Translate Preview", "description": "Gemini 3.5 Live Translate Preview", "version": "3.5-live-translate-06-2026", "input_token_limit": 16384, "output_token_limit": 32768, "methods": ["bidiGenerateContent"], "temperature": 1, "top_p": 0.95, "top_k": 64},
];
